### ISSUE TITLE
Move data to separate module

### ISSUE THREAD

**Issue by davidtheclark** [betit/stylelint-known-property#2]
This is a great plugin idea!

I have been thinking about something similar to be integrated into stylelint core but thought maybe some plugin experimentation should come first, since I don't know if the rule will be buggy & have too many edge cases or not. So I'm really curious to see how this one goes!

I noticed that the property list that the plugin uses would be a good candidate for a separate module, because it could prove useful to all other kinds of CSS tools. I wonder if one already exists? If not, it would be a worthy module to create and maintain --- a reliable list of all standard CSS properties. If an attempt does already exist, maybe it's worthwhile to use it, team-up with those maintainers, and work together to keep the list as accurate as possible?

**Comment by vio** [comment]
Thanks @davidtheclark and thank you for your work on `stylelint`! Really helpful to run the linting task with PostCSS ;)

The plugin is just a simple experiment to see if I can replace csslint with stylelint in my workflow. The main goal is to be able to validate the property name. Will be nice to be able to validate the value as well, but as you said there are a lot of cases.

> I noticed that the property list that the plugin uses would be a good candidate for a separate module, because it could prove useful to all other kinds of CSS tools.
Yes, maybe at one point it can be a distinct package. Atm, the list is not complete, just a fetch from https://developer.mozilla.org/en-US/docs/Web/CSS/Reference (css2.2 + css3 modules + some browser specific properties).

> I wonder if one already exists ?
There are some packages available, like [css-properties](https://www.npmjs.com/package/css-properties), but they contain only a subset of what i think we might need to validate:

- CSS2.2 properties
- CSS3 module properties
- Browser specific properties
- SVG properties

Depending on my available time, will continue to experiment with the data & value validation and will push to a branch. 

Let me know what you thing ;)

**Comment by davidtheclark** [comment]
> The plugin is just a simple experiment to see if I can replace csslint with stylelint in my workflow.

Does CSSLint do this for you -- validate property names and values?

> Browser specific properties

That one I'm sure would be a nightmare. I think it would be totally legitimate to just skip vendor prefixed properties :)

I'll watch the module ... I'm curious how it goes for you! Let me know if you need any help.

**Comment by vio** [comment]
https://github.com/betit/known-css-properties
