### ISSUE TITLE
Converting from a plugin to a core rule?

### ISSUE THREAD

**Issue by jeddy3** [betit/stylelint-known-property#6]
Great job with this plugin. It's looking great.

We have [a proposal](https://github.com/stylelint/stylelint/issues/950) for including such a plugin in stylelint itself. In fact, `property-no-unknown` is one of the last of the `*-no-unknown` rules to complete. We have already released:

- `unit-no-unknown`
- `selector-pseudo-class-no-unknown`
- `selector-pseudo-element-no-unknown`
- `selector-type-no-unknown`

Would you consider migrating this plugin to into stylelint via a Pull Request?

**Comment by vio** [comment]
@jeddy3 No problem in doing that, but we need to sort couple things before:

- [ ] handle the browser prefixes
- [ ] handle CSS hacks
- [ ] have a complete list of CSS properties

We have something in progress, will let you know when they are ready

**Comment by ntwb** [comment]
> handle the browser prefixes

stylelint has the rule ['property-no-vendor-prefix'](https://github.com/stylelint/stylelint/tree/master/src/rules/property-no-vendor-prefix) to handle disallowing vendor prefixes.

> handle CSS hacks

stylelint has the rule ['no-browser-hacks'](https://github.com/stylelint/stylelint/tree/master/src/rules/no-browser-hacks) to handle disallowing CSS hacks

> have a complete list of CSS properties

There are approx half a dozen existing modules, and each were slightly different last time I checked:
• https://www.npmjs.com/search?q=css+properties

The 3 sites I've use when needing to look up CSS proprties (which I think many of the lists are dervived from):
• http://www.quirksmode.org/css/
• http://meiert.com/en/indices/css-properties/
• http://caniuse.com/

**Comment by jeddy3** [comment]
> We have something in progress, will let you know when they are ready

Excellent! Please fire over a PR when you're something to share.

> handle the browser prefixes

In [`selector-pseudo-element-no-unknown`](https://github.com/stylelint/stylelint/tree/master/src/rules/selector-pseudo-element-no-unknown) we [simply ignore](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-pseudo-element-no-unknown/index.js#L47) vendor prefixed pseudo-elements. We do this because, since the emergence of tools like [autoprefixer](https://github.com/postcss/autoprefixer), dealing with prefixes any other way feels like spending a chunk of time on a edge-case.

> handle CSS hacks

I think PostCSS [parses things like the `*` and `_` type hacks](https://astexplorer.net/#/TaB341raJO) into raws and so the clean property name is exposed in the `prop` value. So, hopefully this one just works itself out. Or have you run into property hacks that don't behave this way?

> have a complete list of CSS properties

As @ntwb said, this probably the trickest to resolve.  In [`selector-type-no-unknown`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-type-no-unknown/index.js)  we [consume two 3rd party modules](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-type-no-unknown/index.js#L2-L3) and then [add to those ourselves](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-type-no-unknown/index.js#L21-L45). Perhaps something similar here is needed? 

Good luck and I'm looking forward to seeing this in core and it's an often requested rule :)

**Comment by vio** [comment]
Thanks @ntwb, @jeddy3! 

> handle the browser prefixes

ATM we are removing the prefix and test the property as it is, but there are non standard browser specific properties that will be nice to validate as well (eg: `-webkit-overflow-scrolling`).

My idea was to have the browser specific properties in the list of known properties and validate the full string.

> handle CSS hacks

I was not aware that PostCSS is handling the hacks, no need to do anything for this, thanks @jeddy3!

> have a complete list of CSS properties 

Yes, this seams to be the bigest challange. I already checked more than half of dozen of packages and I couldn't find one that is up to date or complete.  

I'm working at a complete list of properties with all the w3c properties and the browser specific ones.

**Comment by jeddy3** [comment]
> My idea was to have the browser specific properties in the list of known properties and validate the full string.

That works.

> I'm working at a complete list of properties with all the w3c properties and the browser specific ones.

As does this :)

**Comment by ntwb** [comment]
> Yes, this seams to be the bigest challange. I already checked more than half of dozen of packages and I couldn't find one that is up to date or complete.

I just looked at one of those modules thinking `-webkit-overflow-scrolling` might be included as it focuses specifically on the _Chrome, Edge, Firefox, PhantomJS and Safari_ vendors properties but alas it does not, so another case of the many unmaintained libraries out there.

Maybe https://github.com/ben-eb/css-values is worth taking a look at, I know it is not yet complete but contributing back to a fellow PostCSS whose aim is to cover 100% of CSS proprties

**Comment by jeddy3** [comment]
> I just looked at one of those modules thinking -webkit-overflow-scrolling might be included

Thanks for doing this!

> Maybe https://github.com/ben-eb/css-values is worth taking a look at

I think using `css-values` in stylelint is very much the end goal i.e. a `declaration-no-invalid` rule powered by `css-values` will supersede all of the `*-no-known` rules. However, in the short-term I think finishing this `property-unknown` rule and bundling it within stylelint is the best course of action as it'll be immediately useful to lots of users. Maintaining a list of properties somewhere is a viable workaround for now as adding new items to it will be a non-breaking change in stylelint.

After this rule though, I agree that we should push in favour of contributing to `css-value` whenever a new proposal comes up to validate some part of a declaration e.g. https://github.com/stylelint/stylelint/issues/1003

**Comment by ntwb** [comment]
> Maintaining a list of properties somewhere is a viable workaround for now as adding new items to it will be a non-breaking change in stylelint.

Right, this makes sense 👍 

How about `propertyData.js` in `stylelint/stylelint/tree/master/src/reference`?

**Comment by jeddy3** [comment]
> How about propertyData.js in stylelint/stylelint/tree/master/src/reference?

That, or a separate repo. Both would work.

**Comment by vio** [comment]
@jeddy3 / @ntwb We have now a more complete list of CSS properties in a distinct package, [know-css-properties](https://www.npmjs.com/package/known-css-properties):

> Standard properties (only 'CR', 'WD', 'FPWD', 'LC', 'REC' statuses): http://www.w3.org/Style/CSS/all-properties.en.json
> Browser supported properties from` window.getComputedStyle` / `document.body.style`

We still have to review and add couple more supported browsers(old IE, Android Browser), but I think we can have a look at the core plugin now.

**Comment by jeddy3** [comment]
> but I think we can have a look at the core plugin now.

Fantastic!

Good job with the complete list. It looks great.

**Comment by ntwb** [comment]
Awesome 💯
